module Version exposing (..) -- where 
{-| This file is auto-generated by the Python script version.py. -} 


version : String 
version = "v5.0-beta-6-gccc8a21"

gitRepo : String 
gitRepo = "http://github.com/kgashok/fuzzy"

