module Version exposing (..) -- where 
{-| This file is auto-generated by the Python script version.py. -} 


version : String 
version = "v5.0-beta-12-g5e663ed"

gitRepo : String 
gitRepo = "https://github.com/kgashok/fuzzy"

